# Generated by Django 4.2.1 on 2023-07-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('inst_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('inst_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_uid', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('org_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_uid', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('aadhar', models.IntegerField()),
                ('photo', models.ImageField(upload_to='person/')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='resources/')),
            ],
        ),
        migrations.CreateModel(
            name='SevaStore',
            fields=[
                ('seva_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('seva_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_uid', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkInfoByOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.organisation')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.person')),
            ],
        ),
        migrations.CreateModel(
            name='WorkInfoByInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.institution')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.person')),
            ],
        ),
        migrations.CreateModel(
            name='UnorganisedWorkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200)),
                ('seva_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.sevastore')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.person')),
            ],
        ),
        migrations.CreateModel(
            name='SevaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('seva_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.sevastore')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.person')),
            ],
        ),
        migrations.CreateModel(
            name='RolesByOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='RolesByInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.institution')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.organisation')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.person')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.institution')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.person')),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('grade', models.IntegerField()),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.institution')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.person')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.institution')),
            ],
        ),
    ]
