# Generated by Django 4.2.1 on 2023-07-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_remove_post_file_post_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='videofile',
            new_name='file',
        ),
    ]
